<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="3" guice-stage="DEVELOPMENT" name="Failed suite [Suite]" parallel="classes">
  <test name="Test">
    <classes>
      <class name="com.eversource.qa.testcases.EditProfileTest"/>
    </classes>
  </test> <!-- Test -->
  <test name="Test2">
    <classes>
      <class name="com.eversource.qa.testcases.LoginPageTest"/>
    </classes>
  </test> <!-- Test2 -->
  <test name="Test3">
    <classes>
      <class name="com.eversource.qa.testcases.OutageStormTest"/>
    </classes>
  </test> <!-- Test3 -->
  <test name="Test3(failed)" parallel="classes">
    <classes>
      <class name="com.eversource.qa.testcases.EditProfileTest">
        <methods>
          <include name="setUp"/>
          <include name="Flush"/>
        </methods>
      </class> <!-- com.eversource.qa.testcases.EditProfileTest -->
      <class name="com.eversource.qa.testcases.LoginPageTest">
        <methods>
          <include name="Flush"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.eversource.qa.testcases.LoginPageTest -->
      <class name="com.eversource.qa.testcases.OutageStormTest">
        <methods>
          <include name="Flush"/>
          <include name="setup"/>
          <include name="stormOutage"/>
        </methods>
      </class> <!-- com.eversource.qa.testcases.OutageStormTest -->
    </classes>
  </test> <!-- Test3(failed) -->
</suite> <!-- Failed suite [Suite] -->
